### ISSUE TITLE
Ошибка при sampctl package install

### ISSUE THREAD

**Issue by An2An96** [ziggi/samp-plugin-timerfix#2]
Привет, не удается поставить плагин через sampctl, в релизах нет нужных архивов с собранным плагином

`WARN: failed to ensure package github.com/ziggi/samp-plugin-timerfix: failed to ensure asset: failed to get plugin SAMP-git/samp-plugin-timerfix from net: resource matcher '^timerfix-(.*)-win32.zip$' does not match any release assets from '[ timerfix-1.6-linux.tar.gz]'`

**Comment by ziggi** [comment]
Поправил.
